# Generated by Django 5.0.7 on 2024-08-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='video_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
