# Generated by Django 5.0.7 on 2024-07-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('joined_date', models.DateField()),
                ('type_author', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], default='Fulltime', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField(null=True)),
                ('short_detail', models.CharField(max_length=300)),
                ('demo', models.BooleanField(default=False)),
            ],
        ),
    ]
